"use client";
/* eslint-disable @next/next/no-img-element */
import { useState } from "react";
import { useAccount } from "../auth/account-provider";
import { kinds, type Post, type Comment } from "@/app/lib/social/types";
import { Empty, ErrorNote, mutate, PersonLink, time, useAction, useData } from "./common";
const labels={post:"Post",event:"Event poster",location:"Location",after:"After photos",live:"Live event",story:"24-hour story"};
export function Composer({existing,onDone,onCancel}:{existing?:Post;onDone:()=>Promise<void>;onCancel:()=>void}) {
 const [kind,setKind]=useState(existing?.kind||"post"),[mediaId,setMediaId]=useState(existing?.mediaId||"");const a=useAction();
 return <form className="real-card real-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{await mutate("post-save",{id:existing?._id,kind,mediaId,title:f.get("title"),text:f.get("text"),location:f.get("location"),category:f.get("category"),audience:f.get("audience"),price:Number(f.get("price")),latitude:f.get("latitude")===""?null:Number(f.get("latitude")),longitude:f.get("longitude")===""?null:Number(f.get("longitude")),startsAt:f.get("startsAt")?new Date(String(f.get("startsAt"))).toISOString():null,endsAt:f.get("endsAt")?new Date(String(f.get("endsAt"))).toISOString():null});await onDone();onCancel();});}}>
  <div className="real-row"><h2>{existing?"Edit your post":"Make a little noise"}</h2><button type="button" onClick={onCancel}>Cancel</button></div>
  <label>Format<select disabled={!!existing} value={kind} onChange={e=>setKind(e.target.value as Post["kind"])}>{kinds.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>
  <label>Title<input name="title" required maxLength={120} defaultValue={existing?.title}/></label>
  <label>Your words<textarea name="text" maxLength={2000} defaultValue={existing?.text}/></label>
  <label>Photo or poster<input type="file" accept="image/jpeg,image/png,image/webp" disabled={a.busy} onChange={e=>{const file=e.target.files?.[0];if(file)void a.run(async()=>{if(file.size>3*1024*1024)throw Error("Choose an image under 3 MB.");const r=await fetch("/api/media",{method:"POST",headers:{"Content-Type":file.type},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);setMediaId(d.id);});}}/><small>JPEG, PNG or WebP, up to 3 MB.</small></label>
  {mediaId&&<div><img className="real-preview" src={`/api/media/${mediaId}`} alt="Your uploaded image"/><button type="button" onClick={()=>setMediaId("")}>Remove image</button></div>}
  <label>Location<input name="location" maxLength={160} defaultValue={existing?.location}/></label>
  <div className="real-two"><label>Latitude (optional)<input name="latitude" type="number" step="any" min={-90} max={90} defaultValue={existing?.latitude??""}/></label><label>Longitude (optional)<input name="longitude" type="number" step="any" min={-180} max={180} defaultValue={existing?.longitude??""}/></label></div>
  <label>Category<input name="category" maxLength={40} defaultValue={existing?.category} placeholder="Music, food, outdoors…"/></label>
  <div className="real-two"><label>Starts<input name="startsAt" type="datetime-local" required={kind==="event"||kind==="live"} defaultValue={localDate(existing?.startsAt)}/></label><label>Ends<input name="endsAt" type="datetime-local" required={kind==="event"||kind==="live"} defaultValue={localDate(existing?.endsAt)}/></label></div>
  <label>Entry price (CAD)<input name="price" type="number" min={0} max={100000} step="0.01" defaultValue={existing?.price||0}/></label>
  <label>Audience<select name="audience" defaultValue={existing?.audience||"public"}><option value="public">Everyone on BUZZ</option><option value="followers">Followers</option></select><small>A private profile always restricts posts to approved followers.</small></label>
  {kind==="story"&&<p>Your story disappears from BUZZ after 24 hours.</p>}<ErrorNote text={a.error}/><button className="real-primary" disabled={a.busy}>{a.busy?"Saving…":existing?"Save changes":"Publish"}</button>
 </form>;
}
function localDate(v:string|null|undefined){if(!v)return "";const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function Comments({post,onChange}:{post:Post;onChange:()=>Promise<void>}) {
 const {data,error,refresh}=useData<{comments:Comment[]}>("comments",{id:post._id});const account=useAccount();const a=useAction(async()=>{await refresh();await onChange();});const [text,setText]=useState("");
 return <section className="real-comments"><ErrorNote text={error||a.error}/>{data?.comments.map(c=><div key={c._id}><strong><PersonLink id={c.ownerId} name={c.author.name}/></strong><p>{c.text}</p>{(c.ownerId===account.uid||post.ownerId===account.uid)&&<button disabled={a.busy} onClick={()=>void a.run(()=>mutate("comment-delete",{id:c._id}))}>Delete comment</button>}</div>)}<form onSubmit={e=>{e.preventDefault();void a.run(async()=>{await mutate("comment",{id:post._id,text});setText("");});}}><label>Comment<textarea required maxLength={1000} value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={a.busy||!text.trim()}>Reply</button></form></section>;
}
export function PostCard({post:p,refresh}:{post:Post;refresh:()=>Promise<void>}) {
 const account=useAccount();const [edit,setEdit]=useState(false),[comments,setComments]=useState(false);const a=useAction(refresh);const event=p.kind==="event"||p.kind==="live";const ended=!!p.endsAt&&new Date(p.endsAt).getTime()<=Date.now();
 if(edit)return <Composer existing={p} onDone={refresh} onCancel={()=>setEdit(false)}/>;
 return <article className={`real-card real-post kind-${p.kind}`}><header className="real-row"><div><PersonLink id={p.ownerId} name={p.author.name}/><small>@{p.author.handle} · {time(p.createdAt)}</small></div><span className="real-tag">{labels[p.kind]}</span></header>
  {p.mediaId&&<img className="real-media" src={`/api/media/${p.mediaId}`} alt={p.title} loading="lazy"/>}<h2>{p.title}</h2><p className="real-copy">{p.text}</p>
  {p.location&&<p>↗ {p.location}</p>}{p.latitude!==null&&p.longitude!==null&&<a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=16/${p.latitude}/${p.longitude}`}>Open location map ↗</a>}
  {event&&<div className="real-ticket"><strong>{p.here} checked in <span>· {p.going} going</span></strong><p>{p.startsAt&&time(p.startsAt)} → {p.endsAt&&time(p.endsAt)}</p><small>{p.price?`CAD $${p.price.toFixed(2)}`:"Free entry"} · {p.category}</small><div className="real-actions"><button disabled={a.busy||ended} aria-pressed={!!p.attendance} onClick={()=>void a.run(()=>mutate("reaction",{id:p._id,kind:"going",enabled:!p.attendance}))}>{p.attendance?"Cancel attendance":"I'm going"}</button><button disabled={a.busy||ended} aria-pressed={p.attendance==="here"} onClick={()=>void a.run(()=>mutate("reaction",{id:p._id,kind:"here",enabled:p.attendance!=="here"}))}>{p.attendance==="here"?"Check out":"Check in"}</button></div><small>{ended?"This event has ended.":"Check-ins are self-reported attendance."}</small></div>}
  {p.expiresAt&&<small>Disappears {time(p.expiresAt)}</small>}
  <div className="real-actions"><button disabled={a.busy} aria-pressed={p.liked} onClick={()=>void a.run(()=>mutate("reaction",{id:p._id,kind:"like",enabled:!p.liked}))}>{p.liked?"♥":"♡"} {p.likes}</button><button disabled={a.busy} aria-pressed={p.saved} onClick={()=>void a.run(()=>mutate("reaction",{id:p._id,kind:"save",enabled:!p.saved}))}>{p.saved?"Saved":"Save"}</button><button onClick={()=>setComments(!comments)}>Replies · {p.comments}</button>{p.ownerId!==account.uid&&<button disabled={a.busy} onClick={()=>{const reason=prompt("What should the moderators know about this post?");if(reason)void a.run(()=>mutate("report",{id:p._id,kind:"post",reason}));}}>Report</button>}{p.ownerId===account.uid&&<><button onClick={()=>setEdit(true)}>Edit</button><button disabled={a.busy} onClick={()=>{if(confirm("Delete this post?"))void a.run(()=>mutate("post-delete",{id:p._id}));}}>Delete</button></>}</div><ErrorNote text={a.error}/>{comments&&<Comments post={p} onChange={refresh}/>}</article>;
}
export function Feed({params={}}:{params?:Record<string,string>}) {
 const [page,setPage]=useState(0);const {data,error,loading,refresh}=useData<{posts:Post[];more:boolean}>("feed",{...params,page:String(page)},15000);
 return <><ErrorNote text={error}/>{error&&<button onClick={()=>void refresh()}>Retry</button>}{loading&&<p role="status">Loading posts…</p>}{data?.posts.length===0&&<Empty>No posts here yet. When people share something, it will appear here.</Empty>}<div className="real-stack">{data?.posts.map(p=><PostCard key={p._id} post={p} refresh={refresh}/>)}</div><div className="real-actions">{page>0&&<button onClick={()=>setPage(page-1)}>Previous</button>}{data?.more&&<button onClick={()=>setPage(page+1)}>Next</button>}</div></>;
}
