"use client";
import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { PersonCard, PublicProfile } from "@/app/components/social/people";
import { Empty, ErrorNote, useData } from "@/app/components/social/common";
import { Feed } from "@/app/components/social/posts";
import { defaults, type Person, type Post, type Settings } from "@/app/lib/social/types";
function Explore(){
 const router=useRouter();const search=useSearchParams();const person=search.get("person");const [tab,setTab]=useState("people"),[text,setText]=useState(""),[term,setTerm]=useState(""),[map,setMap]=useState(false),[location,setLocation]=useState<{lat:string;lng:string}|null>(null),[geoError,setGeoError]=useState(""),[radiusOverride,setRadius]=useState<number|null>(null),[categoryOverride,setCategory]=useState<string|null>(null),[freeOverride,setFree]=useState<boolean|null>(null);
 const settings=useData<{settings:Settings}>("settings");
 const radius=radiusOverride??settings.data?.settings.radius??25,category=categoryOverride??settings.data?.settings.category??"",free=freeOverride??settings.data?.settings.freeOnly??false;
 useEffect(()=>{const t=setTimeout(()=>setTerm(text),300);return()=>clearTimeout(t);},[text]);
 const people=useData<{people:Person[]}>("users",{q:term});
 const params={events:"1",q:term,category,free:free?"1":"0",radius:String(radius),...(location||{})};
 const events=useData<{posts:Post[]}>("feed",params);const [selected,setSelected]=useState<Post|null>(null);
 if(person)return <main className="real-page"><button onClick={()=>router.push("/explore")}>← Explore</button><PublicProfile key={person} id={person}/></main>;
 const focus=(selected&&events.data?.posts.find(p=>p._id===selected._id))||events.data?.posts.find(p=>p.latitude!==null&&p.longitude!==null);const lat=focus?.latitude,lng=focus?.longitude;
 return <main className="real-page"><p className="real-eyebrow">FIND YOUR PEOPLE</p><h1>Explore the buzz.</h1><div className="real-tabs">{["people","events"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div><label className="real-search">Search {tab}<input type="search" value={text} onChange={e=>setText(e.target.value)} placeholder={tab==="people"?"Name or @handle":"Event, place or keyword"}/></label>
 {tab==="people"?<><ErrorNote text={people.error}/>{people.loading&&<p>Finding people…</p>}{people.data?.people.length===0&&<Empty>No matching people. Try another name or handle.</Empty>}{people.data?.people.map(p=><PersonCard key={p.id} person={p} refresh={people.refresh} onOpen={id=>router.push(`/explore?person=${encodeURIComponent(id)}`)}/>)}</>:<><section className="real-card real-form"><div className="real-two"><label>Category<input value={category} maxLength={40} onChange={e=>setCategory(e.target.value)}/></label><label>Radius (km)<input type="number" min={1} max={200} value={radius||defaults.radius} onChange={e=>setRadius(Number(e.target.value))}/></label></div><label className="real-check"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/> Free events only</label><div className="real-actions"><button onClick={()=>{setGeoError("");if(!navigator.geolocation){setGeoError("Location is unavailable in this browser.");return;}navigator.geolocation.getCurrentPosition(p=>setLocation({lat:String(p.coords.latitude),lng:String(p.coords.longitude)}),()=>setGeoError("Location permission was denied or your location is unavailable."),{timeout:15000});}}>{location?"Refresh my location":"Find events near me"}</button>{location&&<button onClick={()=>setLocation(null)}>Clear location</button>}<button aria-pressed={map} onClick={()=>setMap(!map)}>{map?"Scroll view":"Map view"}</button></div><small>Radius applies after you share your location. Events need coordinates to appear nearby.</small><ErrorNote text={geoError}/></section>
 {map?<section className="real-card"><ErrorNote text={events.error}/>{lat!==null&&lat!==undefined&&lng!==null&&lng!==undefined?<iframe title={`Map: ${focus?.title}`} className="real-map" loading="lazy" src={`https://www.openstreetmap.org/export/embed.html?bbox=${lng-.02}%2C${lat-.02}%2C${lng+.02}%2C${lat+.02}&layer=mapnik&marker=${lat}%2C${lng}`}/>:<Empty>No matching events with map coordinates yet.</Empty>}<div className="real-stack">{events.data?.posts.filter(p=>p.latitude!==null).map(p=><button key={p._id} onClick={()=>setSelected(p)}>{p.title} · {p.location}</button>)}</div><small>Map data © OpenStreetMap contributors</small></section>:<Feed key={JSON.stringify(params)} params={params}/>}</>}
 </main>;
}
export default function Screen(){return <Suspense fallback={<p>Loading Explore…</p>}><Explore/></Suspense>;}