"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import DeleteAccount from "@/app/components/social/delete-account";
import { useAccount } from "@/app/components/auth/account-provider";
import { logOut } from "@/app/lib/auth/flow";
import { defaults, type Person, type Settings } from "@/app/lib/social/types";
import { ErrorNote, mutate, query, useAction, useData } from "@/app/components/social/common";
export function Appearance(){const d=useData<{settings:Settings}>("settings");useEffect(()=>{if(!d.data)return;document.documentElement.dataset.buzzTheme=d.data.settings.theme;document.documentElement.dataset.buzzMotion=d.data.settings.reducedMotion?"reduced":"full";return()=>{delete document.documentElement.dataset.buzzTheme;delete document.documentElement.dataset.buzzMotion;};},[d.data]);return null;}
export default function SettingsScreen(){
 const account=useAccount();const reports=useData<{reports:{_id:string;kind:string;reason:string;snapshot:string;status:string;createdAt:string}[]}>("reports");
 const d=useData<{settings:Settings;blocked:Person[];requests:Person[]}>("settings");const [draft,setDraft]=useState<Settings|null>(null),[notice,setNotice]=useState("");const a=useAction(d.refresh);
 const s=draft??d.data?.settings??defaults;
 const update=<K extends keyof Settings>(key:K,value:Settings[K])=>setDraft({...s,[key]:value});
 const toggle=(key:keyof Settings,label:string,description:string)=><label className="real-setting" key={key}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={Boolean(s[key])} onChange={e=>update(key,e.target.checked as never)}/></label>;
 const select=(key:keyof Settings,label:string,options:string[])=><label key={key}>{label}<select value={String(s[key])} onChange={e=>update(key,e.target.value as never)}>{options.map(o=><option value={o} key={o}>{o}</option>)}</select></label>;
 return <main className="real-page"><p className="real-eyebrow">MAKE ROOM FOR YOURSELF</p><h1>Your BUZZ. Your rules.</h1><ErrorNote text={d.error||a.error}/>{notice&&<p role="status" className="real-notice">{notice}</p>}{d.loading?<p>Loading preferences…</p>:<>
 <section className="real-card"><h2>Account & security</h2><div className="real-stack"><Link href="/profile">Edit name, handle, bio and interests ↗</Link><Link href="/account/security">Password, verified email & connected sign-in accounts ↗</Link></div></section>
 <form className="real-form" onSubmit={e=>{e.preventDefault();void a.run(async()=>{await mutate("settings",{settings:s});document.documentElement.dataset.buzzTheme=s.theme;document.documentElement.dataset.buzzMotion=s.reducedMotion?"reduced":"full";setNotice("Your preferences are saved across devices.");});}}>
 <section className="real-card"><h2>Privacy & boundaries</h2>{toggle("privateProfile","Private profile","Only approved followers can see your posts and events.")}{toggle("discoverable","Appear in people search","Let other users find your profile by name or handle.")}{select("comments","Who can comment",["everyone","followers","nobody"])}{select("messages","Who can message me",["everyone","following","nobody"])}<small>Following means people you follow.</small>{select("groupInvites","Who can add me to groups",["everyone","following","nobody"])}{toggle("readReceipts","Read receipts","Show other participants when you have read their messages.")}</section>
 <section className="real-card"><h2>Activity</h2>{toggle("notifications","In-app activity notifications","Receive new follow, like, comment and message activity on Home.")}</section>
 <section className="real-card"><h2>Discovery & hosting</h2><label>Preferred radius (km)<input type="number" min={1} max={200} value={s.radius} onChange={e=>update("radius",Number(e.target.value))}/></label><label>Preferred event category<input maxLength={40} value={s.category} onChange={e=>update("category",e.target.value)}/></label>{toggle("freeOnly","Free events only","Start Explore with free events selected.")}<label>Default party-room duration (hours)<input type="number" min={0} max={720} value={s.partyHours} onChange={e=>update("partyHours",Number(e.target.value))}/><small>0 keeps the room open. Organisers can set an expiry when creating each room.</small></label></section>
 <section className="real-card"><h2>Appearance & accessibility</h2>{select("theme","Colour theme",["light","dark"])}{toggle("reducedMotion","Reduce motion","Minimise animations and smooth scrolling.")}</section><button className="real-primary" disabled={a.busy}>Save preferences</button></form>
 <section className="real-card"><h2>Follow requests</h2>{!d.data?.requests.length&&<p>No pending requests.</p>}{d.data?.requests.map(p=><div className="real-person" key={p.id}><span>{p.name} <small>@{p.handle}</small></span><button disabled={a.busy} onClick={()=>void a.run(()=>mutate("follow-request",{id:p.id,accept:true}))}>Approve</button><button disabled={a.busy} onClick={()=>void a.run(()=>mutate("follow-request",{id:p.id,accept:false}))}>Decline</button></div>)}</section>
 <section className="real-card"><h2>Blocked accounts</h2>{!d.data?.blocked.length&&<p>No blocked accounts.</p>}{d.data?.blocked.map(p=><div className="real-row" key={p.id}>{p.name}<button disabled={a.busy} onClick={()=>void a.run(()=>mutate("block",{id:p.id,enabled:false}))}>Unblock</button></div>)}</section>
 <section className="real-card"><h2>Your data & sessions</h2><div className="real-stack"><button disabled={a.busy} onClick={()=>void a.run(async()=>{const result=await query("export");const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="buzz-my-data.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Download my profile and authored content</button><button disabled={a.busy} onClick={()=>void a.run(()=>logOut())}>Sign out on this device</button><button disabled={a.busy} onClick={()=>{if(confirm("Sign out on every device?"))void a.run(()=>logOut(true));}}>Sign out everywhere</button></div></section>
 <section className="real-card"><h2>{account.role==="member"?"My reports":"Moderation reports"}</h2><ErrorNote text={reports.error}/>{!reports.data?.reports.length&&<p>No reports.</p>}{reports.data?.reports.map(r=><div className="real-comments" key={r._id}><strong>{r.kind} - {r.status}</strong><p>{r.reason}</p><blockquote className="real-report-snapshot">{r.snapshot}</blockquote>{account.role!=="member"&&r.status==="open"&&<button disabled={a.busy} onClick={()=>void a.run(async()=>{await mutate("report-review",{id:r._id});await reports.refresh();})}>Mark reviewed</button>}</div>)}</section><DeleteAccount/>
 </>}</main>;
}