"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { useLocalState } from "@/app/lib/local-state";
import { defaultProfile, memories, type Memory } from "@/app/lib/profile-data";

import { useProfile, useAccount } from "@/app/components/auth/account-provider";
export default function ProfilePage() {
  const [profile, setProfile] = useProfile();
  const account = useAccount();
  const [saving, setSaving] = useState(false);
  const [draft, setDraft] = useState(defaultProfile);
  const [tab, setTab] = useState("All nights");
  const [featuredId, setFeaturedId] = useLocalState("buzz-featured-memory", "m1");
  const [selected, setSelected] = useState<Memory | null>(null);
  const [notice, setNotice] = useState("");
  const edit = useRef<HTMLDialogElement>(null);
  const detail = useRef<HTMLDialogElement>(null);
  const people = useRef<HTMLDialogElement>(null);
  const [peopleTitle, setPeopleTitle] = useState("Your people");
  const featured = memories.find((memory) => memory.id === featuredId) || memories[0];
  const initials = profile.name.trim().split(/\s+/).map((word) => word[0]).slice(0, 2).join("").toUpperCase();
  const displayed = memories.filter((memory) => tab === "All nights" || memory.kind === tab);
  const share = async () => {
    const text = `${profile.name} on BUZZ · @${profile.handle}\n${profile.bio}`;
    try {
      if (navigator.share) await navigator.share({ title: `${profile.name} · BUZZ`, text });
      else { await navigator.clipboard.writeText(text); setNotice("Profile text copied. Public profile links will come later."); }
    } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setNotice("Sharing isn’t available in this browser. Your handle is @" + profile.handle); }
  };
  return <main className="social-page profile-page">
    <div className="passport-heading"><p className="social-kicker">NO TWO NIGHTS. NO TWO PEOPLE.</p><span>YOUR NIGHT PASSPORT</span></div>
    <section className="identity-card" aria-label="Your profile"><div className="identity-topline"><span>BUZZ / PEOPLE</span><span>{account.role === "member" ? "EDITION 001" : account.role.toUpperCase()}</span></div><div className="identity-main"><div className="identity-avatar"><span>{initials}</span><i aria-hidden="true">✦</i><small>GOOD COMPANY</small></div><div className="identity-name"><span className="identity-city">↗ {profile.city}</span><h1>{profile.name}</h1><p>@{profile.handle}</p></div></div><div className="identity-perforation" /><div className="identity-bio"><p>{profile.bio}</p><span className="identity-mood"><i aria-hidden="true">✳</i> CURRENT FREQUENCY <strong>{profile.mood}</strong></span></div><div className="identity-bottom"><span>EST. 2026</span><span aria-hidden="true">▏▎▎▏▍▏▎▍▏▍▎▏▍▏▎▍▏</span><span>ONE OF ONE ↗</span></div></section>
    <div className="profile-actions"><button onClick={() => { setDraft({ ...profile, interests: [...profile.interests] }); edit.current?.showModal(); }}>Edit my passport <span>↗</span></button><button onClick={share} aria-label="Share profile text">Share <span>↑</span></button><Link href="/settings" aria-label="Profile settings">⚙</Link></div>
    {notice && <p className="inline-notice" role="status">{notice}</p>}
    <section className="profile-connections" aria-label="Profile activity"><button onClick={() => { setPeopleTitle("Following"); people.current?.showModal(); }}><strong>4</strong><span>following</span></button><span className="connections-spark" aria-hidden="true">✳</span><button onClick={() => { setPeopleTitle("Your people"); people.current?.showModal(); }}><strong>4</strong><span>your people</span></button><span className="connections-spark" aria-hidden="true">✳</span><button onClick={() => { setTab("All nights"); document.getElementById("night-collection")?.scrollIntoView({ behavior: "smooth", block: "start" }); }}><strong>03</strong><span>nights collected</span></button></section>
    <div className="profile-interests"><span>MY KIND OF SCENE</span><div>{profile.interests.map((interest) => <span key={interest}>{interest}</span>)}</div></div>
    <section className={`featured-memory ${featured.color}`}><div><p>THE NIGHT I’D RELIVE</p><h2>{featured.title}</h2><span>{featured.place} · {featured.date}</span></div><button aria-label={`Open featured memory ${featured.title}`} onClick={() => { setSelected(featured); detail.current?.showModal(); }}>{featured.symbol}<span>OPEN MEMORY ↗</span></button></section>
    <section id="night-collection" className="night-collection"><div className="collection-heading"><div><p className="social-kicker">A LIFE WELL SPENT OUTSIDE</p><h2>The nights that made me.</h2></div><span aria-hidden="true">↙</span></div><div className="social-filters" role="group" aria-label="Filter profile memories">{["All nights", "Hosted", "Went", "Saved"].map((item) => <button key={item} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div><div className="passport-stamps">{displayed.map((memory, index) => <button className={`passport-stamp ${memory.color}`} key={memory.id} onClick={() => { setSelected(memory); detail.current?.showModal(); }}><span className="stamp-number">0{index + 1}<small>{memory.kind.toUpperCase()}</small></span><span className="stamp-copy"><strong>{memory.title}</strong><small>{memory.place}</small></span><span className="stamp-seal"><span aria-hidden="true">{memory.symbol}</span><small>{memory.date}</small></span></button>)}</div></section>
    <div className="profile-signoff"><span aria-hidden="true">✦</span><p>More than a profile.<br /><em>A little proof you were here.</em></p></div><p className="prototype-note">Sample passport & activity · Your edits are saved on this device.</p>
    <dialog ref={edit} className="social-dialog" aria-labelledby="edit-profile-title"><form className="social-dialog-content" onSubmit={async (event) => { event.preventDefault(); if (saving) return; setSaving(true); const interests = [...new Set(draft.interests.map((interest) => interest.trim()).filter(Boolean))].slice(0, 6); try { await setProfile({ ...draft, name: draft.name.trim(), handle: draft.handle.trim(), city: draft.city.trim(), interests }); edit.current?.close(); setNotice("Passport saved to your account."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save your profile."); } finally { setSaving(false); } }}><div className="dialog-title-row"><div><p className="social-kicker">A LITTLE MORE YOU</p><h2 id="edit-profile-title">Edit your passport.</h2></div><button type="button" className="round-action" onClick={() => edit.current?.close()} aria-label="Close profile editor">✕</button></div><label className="form-label">Name<input required maxLength={45} pattern=".*\S.*" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label className="form-label">Handle<input required maxLength={25} pattern="[a-zA-Z0-9_]+" title="Letters, numbers, and underscores only" value={draft.handle} onChange={(event) => setDraft({ ...draft, handle: event.target.value })} /><small>Demo handle; availability isn’t checked.</small></label><label className="form-label">City<input maxLength={40} value={draft.city} onChange={(event) => setDraft({ ...draft, city: event.target.value })} /></label><label className="form-label">Your story<textarea maxLength={180} rows={3} value={draft.bio} onChange={(event) => setDraft({ ...draft, bio: event.target.value })} /></label><label className="form-label">Current frequency<select value={draft.mood} onChange={(event) => setDraft({ ...draft, mood: event.target.value })}>{["One more song", "Down for anything", "Keeping it low-key", "Meet me outside", "Hosting something good"].map((mood) => <option key={mood}>{mood}</option>)}</select></label><label className="form-label">Your scene<input maxLength={160} value={draft.interests.join(",")} onChange={(event) => setDraft({ ...draft, interests: event.target.value.split(",") })} /><small>Up to six interests, separated by commas.</small></label><button className="social-primary">Save my passport ↗</button></form></dialog>
    <dialog ref={detail} className="social-dialog" aria-labelledby="memory-title"><div className="social-dialog-content"><div className="dialog-title-row"><p className="social-kicker">A STAMP IN YOUR STORY</p><button className="round-action" onClick={() => detail.current?.close()} aria-label="Close memory">✕</button></div>{selected && <><div className={`memory-art ${selected.color}`} aria-hidden="true">{selected.symbol}</div><h2 id="memory-title">{selected.title}</h2><p className="memory-details">{selected.date} · {selected.place} · {selected.kind}</p><p className="social-subtitle">A sample memory card. Event photos and the people you shared it with will live here.</p><button className="social-primary" onClick={() => { setFeaturedId(selected.id); detail.current?.close(); setNotice("Your featured night has been updated."); }}>Feature this on my passport ✦</button></>}</div></dialog>
    <dialog ref={people} className="social-dialog" aria-labelledby="people-title"><div className="social-dialog-content"><div className="dialog-title-row"><h2 id="people-title">{peopleTitle}</h2><button className="round-action" onClick={() => people.current?.close()} aria-label="Close people list">✕</button></div><p className="social-subtitle">Sample connections. Your real circle will live here.</p>{["Maya Chen", "Jamie L.", "Leo Rivera", "Ava M."].map((name) => <div className="person-preview" key={name}><span className="mini-avatar">{name[0]}</span><strong>{name}</strong><span>Demo profile</span></div>)}<Link className="social-primary" href="/message">Go to messages ↗</Link></div></dialog>
  </main>;
}